### PR TITLE
WIP: Use multistage build for docker image

### PR DESCRIPTION
**Pull request by leotrubach**
Notes:
lxml python package building takes a long time, I guess no wheel is available.
test running produces a lot of errors, but i guess we have the same for `master` branch

We need to make sure that all libraries are installed on 2nd stage (python3 musl openssl libxslt tinyxml libxml2 jpeg zlib openjpeg) - probably yes.

### CODE REVIEW

**Comment by bcoles** [comment]
> test running produces a lot of errors, but i guess we have the same for `master` branch

Which errors are you referring to?

You can view the most recent Travis CI logs for `master` branch here:

* https://github.com/smicallef/spiderfoot/runs/1087528572

No errors or failed tests are present; however the following warnings are raised:

```
=============================== warnings summary ===============================

sfcli.py:1311

  /home/travis/build/smicallef/spiderfoot/sfcli.py:1311: DeprecationWarning: invalid escape sequence \_

    s.dprint("\n\

/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docx/section.py:7

  /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docx/section.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

    from collections import Sequence

/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/future/standard_library/__init__.py:65

  /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

    import imp

sfcli.py::FLAKE8

  <unknown>:1311: DeprecationWarning: invalid escape sequence \_

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by leotrubach** [comment]
I mean this one - `docker run --rm spiderfoot -m unittest discover -s test/unit`

**Comment by leotrubach** [comment]
BTW, I created #1008 to fix flake8 warning

**Comment by leotrubach** [comment]
@smicallef can be merged now.

**Pull request merged**
