### PR TITLE
sfp_citadel.py changes.

### PR DESCRIPTION
**Pull request by counterintrusive**
Site has changed domain and they have re-written their API.
I've tested everything below, but you may want to give it a run through before pushing live.
Public API key is now limited to 1,500 searches a day to stop to much overhead.

https://leak-lookup.com/api

### CODE REVIEW

**Comment by bcoles** [comment]
You may wish to change your API key.

**Comment by counterintrusive** [comment]
The API key submitted is the free / public key.

**Comment by bcoles** [comment]
What about this one? `09bc5ad70a1104f2dc81fa8c3ec3243d2`

**Comment by counterintrusive** [comment]
That key was destroyed after testing, appreciate the check response though :+1:

**Comment by smicallef** [comment]
Thanks for the contribution!

**Pull request merged**
