### PR TITLE
Update requirements.txt with all dependencies

### PR DESCRIPTION
**Pull request by dfir-alvin**
Request to add openxmllib dependency into requirements.txt file.

### CODE REVIEW

**Comment by x6xmrjasoncook** [comment]
@**__**

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by x6xmrjasoncook** [comment]
**```

```**

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by x6xmrjasoncook** [comment]
@**@@```
##
```**

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smicallef** [comment]
Issue is no longer relevant since the recent v3 -> master branch merge.

**Pull request closed without merging**
