### PR TITLE
Added two dependencies in order to get docker build working again

### PR DESCRIPTION
**Pull request by buttonfreak**
Docker build failed on Pillow with 2 missing dependencies; jpeg-dev and zlib-dev.

### CODE REVIEW

**Comment by elliotberry** [comment]
@buttonfreak Thanks for this. This had been a pain in the butt for a while. I hope it's merged.

**Comment by lupa18** [comment]
Thanks ! also hope it's merged <3

**Comment by lupa18** [comment]
Btw .. this is not working yet, problems with openxmllib and then other with: "No module named Image"

**Comment by smicallef** [comment]
No longer relevant since the recent v3 -> master branch merge.

**Pull request closed without merging**
