### PR TITLE
[sfp_greynoise] Suggested Update for GreyNoise Lookup

### PR DESCRIPTION
**Pull request by bradchiappetta**
The following includes some recommended updates to the GreyNoise lookup.  Please feel free to accept or reject as makes sense:

List of changes:
- Migrates individual IP lookups to use IP Lookup endpoints
- Adds support for RIOT dataset - IP lookups check both now
- Updated broken Logo Links
- Update GreyNoise Visualizer URLs
- Corrected display for "GreyNoise" from "Greynoise"

### CODE REVIEW

**Comment by smicallef** [comment]
Thanks for this contribution! Is there any way using the Greynoise SDK can be avoided and instead stick with using pure REST? Any additional dependencies can create challenges for various distros to package SpiderFoot, not to mention that we generally want to try and keep the number of dependencies as low as possible.

**Comment by bradchiappetta** [comment]
> Thanks for this contribution! Is there any way using the Greynoise SDK can be avoided and instead stick with using pure REST? Any additional dependencies can create challenges for various distros to package SpiderFoot, not to mention that we generally want to try and keep the number of dependencies as low as possible.

@smicallef : should be all set, I updated everything to use  REST lookups.  Let me know if you need any other changes.

**Comment by smicallef** [comment]
Nice! Thanks!

**Comment by smicallef** [comment]
Looks like a lint check failed - PTAL and I'll merge once tests pass.

**Comment by bradchiappetta** [comment]
> Looks like a lint check failed - PTAL and I'll merge once tests pass.

Okay, I think it is good to go.

**Pull request merged**
