### PR TITLE
Use raw triple quotes (flake8 warning)

### PR DESCRIPTION
**Pull request by leotrubach**

### CODE REVIEW

**Comment by bcoles** [comment]
Thanks. It should also be safe to remove `W605` from the ignored warnings for `sfcli.py` from `setup.cfg` now too.

**Comment by bcoles** [comment]
I noticed you removed both ignores for `sfcli`. `DUO106` is still required to be ignored. Only `W605` should be removed from the ignore list.

**Comment by leotrubach** [comment]
Hmmm... I tried disabling other 2 files and see no errors coming

**Comment by bcoles** [comment]
> 
> 
> Hmmm... I tried disabling other 2 files and see no errors coming

Locally? This is what I use for local testing:

```
python3 -m pytest --flake8 --durations=5 --cov-report html --cov=. .
```

Ensure you're running with DUO tests enabled. The DUO tests should included automatically by the `setup.cfg` configuration. Also, ensure you've installed the dependencies for tests:

```
pip3 install -r requirements_test.txt
```

**Comment by leotrubach** [comment]
```
[flake8]
flake8-max-line-length = 120
max-complexity = 100
select = C,E,F,W,B,DUO
ignore = E501 W503 B006 DUO130
```
with this file I get
```
= 1232 passed, 622 skipped, 2 warnings in 43.09s ====
```

**Comment by bcoles** [comment]
The tests are passing and the changes look good to me. Can you please squash commits. Performing multiple changes, undos and redoes in one PR is confusing and messes up the commit history. Commit messages like `Undo` and `Rollback & mark lines` aren't helpful when reviewing the history to figure out when or why something was changed.

**Pull request merged**
